version: "3.1"
services:
  memcached:
    image: memcached:alpine
    container_name: i-am-avatar-memcached

    mysql:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      container_name: i-am-avatar-mysql
      working_dir: /application
      volumes:
        - .:/application
        - ./mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=db
      ports:
        - "3086:3306"

    webserver:
      image: nginx:alpine
      container_name: i-am-avatar-webserver
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "3081:3081"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: i-am-avatar-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

  node-chat:
      build: chat
      container_name: i-am-avatar-node
      working_dir: /application
      ports:
        - "3000:3000"
      volumes:
        - ./chat/log:/application/log